server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/iotdoancoso?useSSL=false&serverTimezone=UTC
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # Thêm dòng này

  mail:
    host: smtp.gmail.com
    port: 587
    username: quanlisvhs@gmail.com
    password: kjak ucgm bbpj mgdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySuperSecretKeyForJWTWhichIsLongEnough123! # Thay đổi chuỗi bí mật
  expiration: 86400000