server:
  port: 8080
spring:
  datasource:
    url: jdbc:sqlserver://DESKTOP-L285G29\\SQLEXPRESS:1433;databaseName=smarthome;encrypt=true;trustServerCertificate=true
    username: sa
    password: ABC123
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
  spring.jpa.hibernate.ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: quanlisvhs@gmail.com
    password: kjak ucgm bbpj mgdo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: mySuperSecretKeyForJWTWhichIsLongEnough123! # Thay đổi chuỗi bí mật
  expiration: 86400000

